import { RoleEnum } from './role-enum';

export class OptionsList {
  public static Roles: Map<string, string> = new Map([
    [RoleEnum.DOCTOR, 'Médico/a'],
    [RoleEnum.NURSE, 'Enfermero/a']
  ]);

  public static Resources: Map<string, string> = new Map([
    ['allergy-intolerance', 'Alergias e intolerancias'],
    ['condition', 'Condición'],
    ['diagnostic-report', 'Informe diagnóstico'],
    ['observation', 'Observación'],
    ['procedure', 'Procedimiento']
  ]);

  public static ResourceDescription: Map<string, string> = new Map([
    ['allergy-intolerance', 'Riesgo de respuesta fisiológica nociva o indeseable que es única para un individuo y está asociada con la exposición a una sustancia.'],
    ['condition', 'Una condición clínica, problema, diagnóstico u otro evento, situación, problema o concepto clínico que ha aumentado a un nivel de preocupación.'],
    ['diagnostic-report',  `Los hallazgos e interpretación de las pruebas de diagnóstico realizadas en pacientes, grupos de pacientes, dispositivos y ubicaciones,
       y / o muestras derivadas de estos. El informe incluye el contexto clínico, como la solicitud y la información del proveedor, y una combinación de resultados
       atómicos, imágenes, interpretaciones textuales y codificadas, y una representación formateada de los informes de diagnóstico.`],
    ['observation', 'Mediciones y afirmaciones simples hechas sobre un paciente, dispositivo u otro tema.'],
    ['procedure', `Una acción que se realiza o se realizó en o para un paciente. Esto puede ser una intervención física como una operación, o menos invasiva, como
     servicios a largo plazo, asesoramiento o hipnoterapia.`]
  ]);

  public static IdentificationTypes: Map<string, string> = new Map([
    ['CC', 'Cédula de Ciudadanía'],
    ['CE', 'Cédula de Extranjería'],
    ['RC', 'Registro Civil'],
    ['TI', 'Tarjeta de Identidad']
  ]);

  public static AddressUses: Map<string, string> = new Map([
    ['home',  'Casa'],
    ['work', 'Oficina'],
    ['temp', 'Temporal'],
    ['old', 'Antiguo'],
    ['billing', 'Facturación']
  ]);

  public static contactPointUses: Map<string, string> = new Map([
    ['home', 'Casa'],
    ['work', 'Oficina'],
    ['temp', 'Temporal'],
    ['old', 'Anterior'],
    ['mobile', 'Celular']
  ]);

  public static contactPointSystems: Map<string, string> = new Map([
    ['phone', 'Teléfono'],
    ['fax', 'Fax'],
    ['email', 'Email'],
    ['sms', 'SMS'],
    ['other', 'Otro']
  ]);

  public static AllergyClinicalStatus: Map<string, string> = new Map([
    [ 'active', 'Activo' ],
    [ 'inactive', 'Inactivo' ],
    [ 'resolved', 'Resuelto' ]
  ]);

  public static AllergyVerificationStatus: Map<string, string> = new Map([
    [ 'unconfirmed', 'No confirmado' ],
    [ 'confirmed', 'Confirmado' ],
    [ 'refuted', 'Refutado' ],
    [ 'entered-in-error', 'Ingresado por error' ]
  ]);

  public static AllergyIntoleranceType: Map<string, string> = new Map([
    [ 'allergy', 'Alergia' ],
    [ 'intolerance', 'Intolerancia' ]
  ]);

  public static AllergyIntoleranceCategory: Map<string, string> = new Map([
    [ 'food', 'Comida' ],
    [ 'medication', 'Medicación' ],
    [ 'environment', 'Ambiente' ],
    [ 'biologic', 'Biologico' ]
  ]);

  public static AllergyIntoleranceCriticality: Map<string, string> = new Map([
    [ 'low', 'Bajo riesgo' ],
    [ 'high', 'Alto riesgo' ],
    [ 'unable-to-assess', 'No se puede evaluar' ]
  ]);

  public static AllergyIntoleranceCodes: Map<string, string> = new Map([
    [ '102002', 'Hemoglobina okaloosa' ],
    [ '120006', 'Carrera de ornitina' ],
    [ '125001', 'Sulfato ferroso Fe ^ 59 ^' ],
    [ '126000', 'Galactosil-N-acetilglucosaminilgalactosilglucosilceramida alfa-galactosiltransferasa' ],
    [ '130002', 'Hemoglobina Hopkins-II' ],
    [ '131003', 'Manosiltransferasa de dolilfosfato' ],
    [ '159002', 'Sal de ferrocianuro' ],
    [ '164003', 'Fosfoenolpiruvato-proteína fosfotransferasa' ],
    [ '178002', 'Uridil difosfato galactosa' ],
    [ '186002', 'Antígeno HLA-Cw9' ]
  ]);

  public static AllergyIntoleranceSeverity: Map<string, string> = new Map([
    [ 'mild', 'Leve' ],
    [ 'moderate', 'Moderada' ],
    [ 'severe', 'Grave' ]
  ]);

  public static ExposureRouteCodes: Map<string, string> = new Map([
    [ '6064005', 'Ruta tópica' ],
    [ '10547007', 'Uso auricular' ],
    [ '12130007', 'Ruta intraarticular' ],
    [ '26643006', 'Uso oral' ],
    [ '34206005', 'Uso de SC' ],
    [ '37161004', 'Uso rectal' ],
    [ '37737002', 'Uso intraluminal' ],
    [ '37839007', 'Uso sublingual' ],
    [ '38239002', 'Uso intraperitoneal' ],
    [ '45890007', 'Uso transdérmico' ]
  ]);

  public static ClinicalFindingsCodes: Map<string, string> = new Map([
    [ '109006', 'Trastorno de ansiedad de la infancia o adolescencia' ],
    [ '122003', 'Hemorragia coroidea' ],
    [ '127009', 'Aborto espontáneo con laceración del cuello uterino.' ],
    [ '129007', 'Homoiotermia' ],
    [ '134006', 'Disminución del crecimiento del cabello.' ],
    [ '140004', 'Faringitis crónica' ],
    [ '144008', 'Visión periférica normal' ],
    [ '147001', 'Cuerpo extraño superficial del escroto sin herida abierta importante pero con infección' ],
    [ '150003', 'Continencia de vejiga anormal' ],
    [ '151004', 'Meningitis por gonococo' ]
  ]);

  public static diagnosticStatusCodes: Map<string, string> = new Map([
    [ 'registered', 'Registrado' ],
    [ 'partial', 'Parcial' ],
    [ 'preliminary', 'Preliminar' ],
    [ 'final', 'Final' ],
    [ 'amended', 'Modificado' ],
    [ 'corrected', 'Corregido' ],
    [ 'appended', 'Adjunto' ],
    [ 'cancelled', 'Cancelado' ],
    [ 'entered-in-error', 'Ingresado por error' ],
    [ 'unknown', 'Desconocido' ]
  ]);

  public static diagnosticCategoryCodes: Map<string, string> = new Map([
    [ 'AU', 'Audiología' ],
    [ 'BG', 'Gases en sangre' ],
    [ 'BLB', 'Banco de Sangre' ],
    [ 'CG', 'Citogenética' ],
    [ 'CH', 'Química' ],
    [ 'CP', 'Citopatología' ],
    [ 'CT', 'Análisis de gato' ],
    [ 'CTH', 'Cateterización cardiaca' ],
    [ 'CUS', 'Ultrasonido cardiaco' ],
    [ 'EC', 'Electrocardíaco (p. Ej., EKG, EEC, Holter)' ],
    [ 'EN', 'Electroneuro (EEG, EMG, EP, PSG)' ],
    [ 'GE', 'Genética' ],
    [ 'HM', 'Hematología' ],
    [ 'ICU', 'Monitoreo de UCI a pie de cama' ],
    [ 'IMM', 'Inmunología' ],
    [ 'LAB', 'Laboratorio' ],
    [ 'MB', 'Microbiología' ],
    [ 'MCB', 'Micobacteriología' ],
    [ 'MYC', 'Micología' ],
    [ 'NMR', 'Resonancia magnética nuclear' ],
    [ 'NMS', 'Exploración de medicina nuclear' ],
    [ 'NRS', 'Medidas de servicio de enfermería' ],
    [ 'OSL', 'Laboratorio exterior' ],
    [ 'OT', 'Terapia ocupacional' ],
    [ 'OTH', 'Otro' ],
    [ 'OUS', 'Ultrasonido OB' ],
    [ 'PF', 'Función pulmonar' ],
    [ 'PHR', 'Farmacia' ],
    [ 'PHY', 'Médico (Hx. Dx, nota de admisión, etc.)' ],
    [ 'PT', 'Terapia física' ],
    [ 'RAD', 'Radiología' ],
    [ 'RC', 'Cuidado respiratorio (terapia)' ],
    [ 'RT', 'Terapia de radiación' ],
    [ 'RUS', 'Ultrasonido Radiológico' ],
    [ 'RX', 'Radiografía' ],
    [ 'SP', 'Patología Quirúrgica' ],
    [ 'SR', 'Serología' ],
    [ 'TX', 'Toxicología' ],
    [ 'VR', 'Virología' ],
    [ 'VUS', 'Ultrasonido vascular' ],
    [ 'XRC', 'Cineradiografía' ]
  ]);

  public static LOINCCodes: Map<string, string> = new Map([
    [ '1-8', 'Aciclovir [Susceptibilidad]' ],
    [ '10-9', 'Amdinocillin [Susceptibilidad] por título bactericida en suero' ],
    [ '100-8', 'Cefoperazona [Susceptibilidad] por concentración inhibitoria mínima (MIC)' ],
    [ '1000-9', 'DBG Ab [Presencia] en suero o plasma de la unidad de producto de sangre' ],
    [ '10000-8', 'Duración de la onda R en AVR principal' ],
    [ '10001-6', 'Duración de la onda R en la derivación I' ],
    [ '10002-4', 'Duración de la onda R en la derivación II' ],
    [ '10003-2', 'Duración de la onda R en la derivación III' ],
    [ '10004-0', 'Duración de la onda R en la derivación V1' ]
  ]);

  public static ConditionClinicalStatus: Map<string, string> = new Map([
    [ 'active', 'Activo' ],
    [ 'recurrence', 'Reaparición' ],
    [ 'relapse', 'Recaída' ],
    [ 'inactive', 'Inactivo' ],
    [ 'remission', 'Remisión' ]
  ]);

  public static ConditionVerificationStatus: Map<string, string> = new Map([
    [ 'unconfirmed', 'No confirmado' ],
    [ 'provisional', 'Provisional' ],
    [ 'differential', 'Diferencial' ],
    [ 'confirmed', 'Confirmado' ],
    [ 'refuted', 'Refutado' ]
  ]);

  public static BodyStructure: Map<string, string> = new Map([
    [ '106004', 'Región carpiana posterior' ],
    [ '107008', 'Parte fetal de la placenta' ],
    [ '108003', 'Vena emisaria condilar' ],
    [ '110001', 'Capa visceral de la cápsula de Bowman' ],
    [ '111002', 'Glándula paratiroidea' ],
    [ '116007', 'Tejido subcutáneo de la superficie medial del dedo índice.' ],
    [ '124002', 'Proceso coronoide de la mandíbula.' ],
    [ '149003', 'Par central de microtúbulos, cilio o flagelo, no bacteriano' ],
    [ '155008', 'Arteria circunfleja profunda del ilion' ],
    [ '167005', 'Parte supraclavicular del plexo braquial.' ],
    [ '202009', 'División anterior de la arteria renal' ],
    [ '205006', 'Comisura izquierda de la válvula aórtica' ],
    [ '206007', 'Músculo glúteo mayor' ],
    [ '221001', 'Superficie articular, falanges, del cuarto hueso metacarpiano' ],
    [ '227002', 'Canal de Hering' ],
    [ '233006', 'Ligamento hepatocólico' ],
    [ '235004', 'Arteria labial superior' ],
    [ '246001', 'Núcleo vestibular lateral' ],
    [ '247005', 'Mesotímpano' ],
    [ '251007', 'Región pectoral' ],
    [ '256002', 'Célula de Kupffer' ],
    [ '263002', 'Nervio torácico' ],
    [ '266005', 'Lóbulo inferior derecho del pulmón' ],
    [ '272005', 'Proceso articular superior de la vértebra lumbar' ],
    [ '273000', 'Miocardio lateral' ],
    [ '283001', 'Ganglio central axilar' ],
    [ '284007', 'Tendón flexor y vaina tendinosa del cuarto dedo del pie' ]
  ]);

  public static ObservationStatus: Map<string, string> = new Map([
    [ 'registered', 'Registrado' ],
    [ 'preliminary', 'Preliminar' ],
    [ 'final', 'Final' ],
    [ 'amended', 'Modificado' ],
    [ 'corrected', 'Corregido' ],
    [ 'cancelled', 'Cancelado' ],
    [ 'entered-in-error', 'Ingresado por error' ],
    [ 'unknown', 'Desconocido' ]
  ]);

  public static ObservationCategory: Map<string, string> = new Map([
    [ 'social-history', 'Historia social' ],
    [ 'vital-signs', 'Signos vitales' ],
    [ 'imaging', 'Imagen' ],
    [ 'laboratory', 'Laboratorio' ],
    [ 'procedure', 'Procedimiento' ],
    [ 'survey', 'Encuesta' ],
    [ 'exam', 'Examen' ],
    [ 'therapy', 'Terapia' ],
    [ 'activity', 'Actividad' ]
  ]);

  public static ObservationInterpretationCodes: Map<string, string> = new Map([
    [ 'CAR', 'Portador' ],
    [ 'B', 'Mejora' ],
    [ 'D', 'Cambio significativo positivo' ],
    [ 'U', 'Cambio significativo negativo' ],
    [ 'W', 'Peor' ],
    [ '<', 'Fuera de escala bajo' ],
    [ '>', 'Fuera de escala alto' ],
    [ 'IE', 'Evidencia insuficiente' ],
    [ 'A', 'Anormal' ],
    [ 'AA', 'Crítica anormal' ],
    [ 'HH', 'Alto crítico' ],
    [ 'LL', 'Bajo crítico' ],
    [ 'H', 'Alto' ],
    [ 'HU', 'Significativamente alto' ],
    [ 'L', 'Bajo' ],
    [ 'LU', 'Significativamente bajo' ],
    [ 'N', 'Normal' ],
    [ 'I', 'Intermedio' ],
    [ 'NCL', 'Sin punto de corte definido por CLSI' ],
    [ 'NS', 'No susceptible' ],
    [ 'R', 'Resistente' ],
    [ 'SYN-R', 'Sinergia - resistente' ],
    [ 'S', 'Susceptible' ],
    [ 'SDD', 'Susceptible a dosis dependientes' ],
    [ 'SYN-S', 'Sinergia - susceptible' ],
    [ 'EX', 'umbral exterior' ],
    [ 'HX', 'por encima del umbral alto' ],
    [ 'LX', 'por debajo del umbral bajo' ],
    [ 'IND', 'Indeterminado' ],
    [ 'E', 'Equívoco' ],
    [ 'NEG', 'Negativo' ],
    [ 'ND', 'No detectado' ],
    [ 'POS', 'Positivo' ],
    [ 'DET', 'Detectado' ],
    [ 'EXP', 'Esperado' ],
    [ 'UNE', 'Inesperado' ],
    [ 'NR', 'No reactivo' ],
    [ 'RR', 'Reactivo' ],
    [ 'WR', 'Débilmente reactivo' ]
  ]);

  public static ObservationMethod: Map<string, string> = new Map([
    [ '58207001', 'Técnica competitiva de ensayo de unión a proteínas' ],
    [ '115341008', 'Medida total' ],
    [ '246363001', 'Técnica de adquisición' ],
    [ '246502009', 'Técnica de llenado de la vejiga' ],
    [ '246503004', 'Técnica de movimiento del catéter' ],
    [ '246504005', 'Técnica de lectura cercana' ],
    [ '246505006', 'Técnica de detección de fotones' ],
    [ '246506007', 'Técnica de provocación' ],
    [ '246507003', 'Técnica de estimulación' ],
    [ '255459008', 'Destello' ],
    [ '255463001', 'Técnica de tetania simple' ],
    [ '255583002', 'Técnica de relación mandibular retruida' ],
    [ '256233002', 'Solución salina infundida rectalmente' ]
  ]);

  public static ProcedureStatus: Map<string, string> = new Map([
    [ 'preparation', 'Preparación' ],
    [ 'in-progress', 'En progreso' ],
    [ 'not-done', 'No hecho' ],
    [ 'on-hold', 'En espera' ],
    [ 'stopped', 'Detenido' ],
    [ 'completed', 'Terminado' ],
    [ 'entered-in-error', 'Ingresado por error' ],
    [ 'unknown', 'Desconocido' ]
  ]);

  public static ProcedureStatusReason: Map<string, string> = new Map([
    [ '135809002', 'Nitrato contraindicado' ],
    [ '135811006', 'Diurético contraindicado' ],
    [ '135822005', 'Tratamiento hipolipemiante contraindicado' ],
    [ '135823000', 'Bloqueador de canales de calcio contraindicado' ],
    [ '169551000', 'Anticoncepción contraindicada' ],
    [ '170954008', 'La terapia de reemplazo hormonal (TRH) está contraindicada' ],
    [ '171277005', 'Sensibilidad C / I - inmunización' ],
    [ '171284002', 'Vacuna contra la tos ferina contraindicada' ],
    [ '183934000', 'Sensibilidad contraindicación al procedimiento' ],
    [ '183936003', 'Contraindicación para la inmunización viva.' ],
    [ '266757004', 'Contraindicación médica del procedimiento.' ],
    [ '266758009', 'Vacuna contraindicada' ]
  ]);

  public static ProcedureCategory: Map<string, string> = new Map([
    [ '24642003', 'Procedimiento o servicio de psiquiatría' ],
    [ '409063005', 'Asesoramiento' ],
    [ '409073007', 'Educación' ],
    [ '387713003', 'Procedimiento quirúrgico' ],
    [ '103693007', 'Procedimiento de diagnóstico' ],
    [ '46947000', 'Manipulación quiropráctica' ],
    [ '410606002', 'Procedimiento de servicio social' ]
  ]);

  public static ProcedureCodes: Map<string, string> = new Map([
    [ '104001', 'Escisión de lesión de rótula' ],
    [ '115006', 'Colocar aparato de ortodoncia extraíble' ],
    [ '119000', 'Lobectomía parcial toracoscópica de pulmón' ],
    [ '121005', 'Inyección retrobulbar de agente terapéutico' ],
    [ '128004', 'Examen con microscopio de mano de la piel.' ],
    [ '133000', 'Implantación percutánea de electrodos neuroestimuladores en el componente neuromuscular' ],
    [ '135007', 'Artrotomía de la articulación de la muñeca con exploración y biopsia.' ],
    [ '142007', 'Escisión del tumor del área del hombro, profunda, intramuscular.' ],
    [ '146005', 'Reparación de la no unión del metatarsiano con injerto óseo' ],
    [ '153001', 'Cistouretroscopia con resección de ureterocele' ],
    [ '160007', 'Extracción de cuerpo extraño de tendón y / o vaina de tendón' ],
    [ '166001', 'Terapia de comportamiento' ]
  ]);

  public static ProcedureOutcome: Map<string, string> = new Map([
    [ '385669000', 'Exitoso' ],
    [ '385671000', 'Fracasado' ],
    [ '385670004', 'Parcialmente exitoso' ]
  ]);

  public static ProcedureFollowUp: Map<string, string> = new Map([
    [ '18949003', 'Cambio de vendaje' ],
    [ '30549001', 'Retirada de sutura' ],
    [ '241031001', 'Retirada del drenaje' ],
    [ '35963001', 'Retirada de grapas' ],
    [ '225164002', 'Remoción de ligadura' ],
    [ '447346005', 'Prueba de ejercicio cardiopulmonar' ],
    [ '229506003', 'Masaje de tejido cicatricial' ],
    [ '274441001', 'Drenaje por succión' ],
    [ '394725008', 'Revisión de medicamentos para la diabetes' ],
    [ '359825008', 'Citopatología, revisión de muestra de lavado bronquioalveolar' ]
  ]);

  public static cities = [
    'Abejorral',
    'Ábrego',
    'Abriaquí',
    'Acacías',
    'Acandí',
    'Acevedo',
    'Achí',
    'Agrado',
    'Agua de Dios',
    'Aguachica',
    'Aguada',
    'Aguadas',
    'Aguazul',
    'Agustín Codazzi',
    'Aipe',
    'Albán',
    'Albania',
    'Albania',
    'Albania',
    'Alcalá',
    'Aldana',
    'Alejandría',
    'Algarrobo',
    'Algeciras',
    'Almaguer',
    'Almeida',
    'Alpujarra',
    'Altamira',
    'Alto Baudó',
    'Altos del Rosario',
    'Alvarado',
    'Amagá',
    'Amalfi',
    'Ambalema',
    'Anapoima',
    'Ancuya',
    'Andalucía',
    'Andes',
    'Angelópolis',
    'Angostura',
    'Anolaima',
    'Anorí',
    'Anserma',
    'Ansermanuevo',
    'Anzá',
    'Anzoátegui',
    'Apartadó',
    'Apía',
    'Apulo',
    'Aquitania',
    'Aracataca',
    'Aranzazu',
    'Aratoca',
    'Arauca',
    'Arauquita',
    'Arbeláez',
    'Arboleda',
    'Arboledas',
    'Arboletes',
    'Arcabuco',
    'Arenal',
    'Argelia',
    'Argelia',
    'Argelia',
    'Ariguaní',
    'Arjona',
    'Armenia',
    'Armenia',
    'Armero',
    'Arroyohondo',
    'Astrea',
    'Ataco',
    'Ayapel',
    'Bagadó',
    'Bahía Solano',
    'Bajo Baudó',
    'Balboa',
    'Balboa',
    'Baranoa',
    'Baraya',
    'Barbacoas',
    'Barbosa',
    'Barbosa',
    'Barichara',
    'Barranca de Upía',
    'Barrancabermeja',
    'Barrancas',
    'Barranco de Loba',
    'Barranquilla',
    'Becerril',
    'Belalcázar',
    'Belén',
    'Belén',
    'Belén de los Andaquíes',
    'Belén de Umbría',
    'Bello',
    'Belmira',
    'Beltrán',
    'Berbeo',
    'Betania',
    'Betéitiva',
    'Betulia',
    'Betulia',
    'Bituima',
    'Boavita',
    'Bochalema',
    'Bogotá',
    'Bojacá',
    'Bojayá',
    'Bolívar',
    'Bolívar',
    'Bolívar',
    'Bolívar',
    'Bosconia',
    'Boyacá',
    'Brazuelo de Papayal',
    'Briceño',
    'Briceño',
    'Bucaramanga',
    'Bucarasica',
    'Buenaventura',
    'Buenavista',
    'Buenavista',
    'Buenavista',
    'Buenavista',
    'Buenos Aires',
    'Buesaco',
    'Buga',
    'Bugalagrande',
    'Buriticá',
    'Busbanzá',
    'Cabrera',
    'Cabrera',
    'Cabuyaro',
    'Cáceres',
    'Cachipay',
    'Cáchira',
    'Cácota',
    'Caicedo',
    'Caicedonia',
    'Caimito',
    'Cajamarca',
    'Cajibío',
    'Cajicá',
    'Calamar',
    'Calamar',
    'Calarcá',
    'Caldas',
    'Caldas',
    'Caldono',
    'Cali',
    'California',
    'Calima',
    'Caloto',
    'Campamento',
    'Campo de la Cruz',
    'Campoalegre',
    'Campohermoso',
    'Canalete',
    'Candelaria',
    'Candelaria',
    'Cantagallo',
    'Cantón de San Pablo',
    'Cañasgordas',
    'Caparrapí',
    'Capitanejo',
    'Cáqueza',
    'Caracolí',
    'Caramanta',
    'Carcasí',
    'Carepa',
    'Carmen de Apicalá',
    'Carmen de Carupa',
    'Carolina del Príncipe',
    'Cartagena de Indias',
    'Cartagena del Chairá',
    'Cartago',
    'Carurú',
    'Casabianca',
    'Castilla la Nueva',
    'Caucasia',
    'Cepitá',
    'Cereté',
    'Cerinza',
    'Cerrito',
    'Cerro de San Antonio',
    'Cértegui',
    'Chachagüí',
    'Chaguaní',
    'Chalán',
    'Chámeza',
    'Chaparral',
    'Charalá',
    'Charta',
    'Chía',
    'Chibolo',
    'Chigorodó',
    'Chima',
    'Chimá',
    'Chimichagua',
    'Chinácota',
    'Chinavita',
    'Chinchiná',
    'Chinú',
    'Chipaque',
    'Chipatá',
    'Chiquinquirá',
    'Chíquiza',
    'Chiriguaná',
    'Chiscas',
    'Chita',
    'Chitagá',
    'Chitaraque',
    'Chivatá',
    'Chivolo',
    'Chivor',
    'Choachí',
    'Chocontá',
    'Cicuco',
    'Ciénaga',
    'Ciénaga de Oro',
    'Ciénega',
    'Cimitarra',
    'Circasia',
    'Cisneros',
    'Clemencia',
    'Cocorná',
    'Coello',
    'Cogua',
    'Colombia',
    'Colón',
    'Colón',
    'Colosó',
    'Cómbita',
    'Concepción',
    'Concepción',
    'Concordia',
    'Concordia',
    'Condoto',
    'Confines',
    'Consacá',
    'Contadero',
    'Contratación',
    'Convención',
    'Copacabana',
    'Coper',
    'Córdoba',
    'Córdoba',
    'Córdoba',
    'Corinto',
    'Coromoro',
    'Corozal',
    'Corrales',
    'Cota',
    'Cotorra',
    'Covarachía',
    'Coveñas',
    'Coyaima',
    'Cravo Norte',
    'Cuaspud',
    'Cubará',
    'Cubarral',
    'Cucaita',
    'Cucunubá',
    'Cúcuta',
    'Cucutilla',
    'Cuítiva',
    'Cumaral',
    'Cumaribo',
    'Cumbal',
    'Cumbitara',
    'Cunday',
    'Curillo',
    'Curití',
    'Curumaní',
    'Dabeiba',
    'Dagua',
    'Dibulla',
    'Distracción',
    'Dolores',
    'Donmatías',
    'Dosquebradas',
    'Duitama',
    'Duranía',
    'Ebéjico',
    'El Águila',
    'El Atrato',
    'El Bagre',
    'El Banco',
    'El Cairo',
    'El Calvario',
    'El Carmen',
    'El Carmen de Atrato',
    'El Carmen de Bolívar',
    'El Carmen de Chucurí',
    'El Carmen de Viboral',
    'El Carmen del Darién',
    'El Castillo',
    'El Cerrito',
    'El Charco',
    'El Cocuy',
    'El Colegio',
    'El Copey',
    'El Doncello',
    'El Dorado',
    'El Dovio',
    'El Espinal',
    'El Espino',
    'El Guacamayo',
    'El Guamo',
    'El Molino',
    'El Paso',
    'El Paujil',
    'El Peñol',
    'El Peñol',
    'El Peñón',
    'El Peñón',
    'El Peñón',
    'El Piñón',
    'El Pital',
    'El Playón',
    'El Retén',
    'El Retiro',
    'El Retorno',
    'El Roble',
    'El Rosal',
    'El Rosario',
    'El Santuario',
    'El Socorro',
    'El Tablón',
    'El Tambo',
    'El Tambo',
    'El Tarra',
    'El Zulia',
    'Elías',
    'Encino',
    'Entrerríos',
    'Envigado',
    'Facatativá',
    'Falán',
    'Filadelfia',
    'Filandia',
    'Firavitoba',
    'Flandes',
    'Florencia',
    'Florencia',
    'Floresta',
    'Florián',
    'Florida',
    'Floridablanca',
    'Fómeque',
    'Fonseca',
    'Fortul',
    'Fosca',
    'Francisco Pizarro',
    'Fredonia',
    'Fresno',
    'Frontino',
    'Fuente de Oro',
    'Fundación',
    'Funes',
    'Funza',
    'Fúquene',
    'Fusagasugá',
    'Gachalá',
    'Gachancipá',
    'Gachantivá',
    'Gachetá',
    'Galán',
    'Galapa',
    'Galeras',
    'Gama',
    'Gamarra',
    'Gámbita',
    'Gámeza',
    'Garagoa',
    'Garzón',
    'Génova',
    'Gigante',
    'Ginebra',
    'Giraldo',
    'Girardot',
    'Girardota',
    'Girón',
    'Gómez Plata',
    'González',
    'Gramalote',
    'Granada',
    'Granada',
    'Granada',
    'Guaca',
    'Guacamayas',
    'Guacarí',
    'Guachené',
    'Guachetá',
    'Guachucal',
    'Guadalupe',
    'Guadalupe',
    'Guadalupe',
    'Guaduas',
    'Guaitarilla',
    'Gualmatán',
    'Guamal',
    'Guamal',
    'Guamo',
    'Guapí',
    'Guapotá',
    'Guaranda',
    'Guarne',
    'Guasca',
    'Guatapé',
    'Guataquí',
    'Guatavita',
    'Guateque',
    'Guática',
    'Guavatá',
    'Guayabal de Síquima',
    'Guayabetal',
    'Guayatá',
    'Güepsa',
    'Güicán',
    'Gutiérrez',
    'Hacarí',
    'Hatillo de Loba',
    'Hato Corozal',
    'Hato',
    'Hatonuevo',
    'Heliconia',
    'Herrán',
    'Herveo',
    'Hispania',
    'Hobo',
    'Honda',
    'Ibagué',
    'Icononzo',
    'Iles',
    'Imués',
    'Inírida',
    'Inzá',
    'Ipiales',
    'Íquira',
    'Isnos',
    'Itagüí',
    'Istmina',
    'Ituango',
    'Iza',
    'Jambaló',
    'Jamundí',
    'Jardín',
    'Jenesano',
    'Jericó',
    'Jericó',
    'Jerusalén',
    'Jesús María',
    'Jordán',
    'Juan de Acosta',
    'Junín',
    'Juradó',
    'La Apartada',
    'La Argentina',
    'La Belleza',
    'La Calera',
    'La Capilla',
    'La Ceja',
    'La Celia',
    'La Cruz',
    'La Cumbre',
    'La Dorada',
    'La Esperanza',
    'La Estrella',
    'La Florida',
    'La Gloria (Cesar)',
    'La Jagua de Ibirico',
    'La Jagua del Pilar',
    'La Llanada',
    'La Macarena',
    'La Merced',
    'La Mesa',
    'La Montañita',
    'La Palma',
    'La Paz',
    'La Paz',
    'La Peña',
    'La Pintada',
    'La Plata',
    'La Playa de Belén',
    'La Primavera',
    'La Salina',
    'La Sierra',
    'La Tebaida',
    'La Tola',
    'La Uvita',
    'La Unión',
    'La Unión',
    'La Unión',
    'La Unión',
    'La Uribe',
    'La Vega',
    'La Vega',
    'La Victoria',
    'La Victoria',
    'La Virginia',
    'Labateca',
    'Labranzagrande',
    'Landázuri',
    'Lebrija',
    'Leiva',
    'Lejanías',
    'Lenguazaque',
    'Lérida',
    'Leticia',
    'Líbano',
    'Liborina',
    'Linares',
    'Litoral de San Juan',
    'Lloró',
    'López de Micay',
    'Lorica',
    'Los Andes',
    'Los Córdobas',
    'Los Palmitos',
    'Los Patios',
    'Los Santos',
    'Lourdes',
    'Luruaco',
    'Macanal',
    'Macaravita',
    'Maceo',
    'Machetá',
    'Madrid',
    'Magangué',
    'Magüí Payán',
    'Mahates',
    'Maicao',
    'Majagual',
    'Málaga',
    'Malambo',
    'Mallama',
    'Manatí',
    'Manaure Balcón del Cesar',
    'Manaure',
    'Maní',
    'Manizales',
    'Manta',
    'Manzanares',
    'Mapiripán',
    'Margarita',
    'María la Baja',
    'Marinilla',
    'Maripí',
    'Mariquita',
    'Marmato',
    'Marquetalia',
    'Marsella',
    'Marulanda',
    'Matanza',
    'Medellín',
    'Medio Atrato',
    'Medio Baudó',
    'Medio San Juan',
    'Medina',
    'Melgar',
    'Mercaderes',
    'Mesetas',
    'Miraflores',
    'Miraflores',
    'Miranda',
    'Mistrató',
    'Mitú',
    'Mocoa',
    'Mogotes',
    'Molagavita',
    'Momil',
    'Mompós',
    'Mongua',
    'Monguí',
    'Moniquirá',
    'Montebello',
    'Montecristo',
    'Montelíbano',
    'Montenegro',
    'Montería',
    'Monterrey',
    'Moñitos',
    'Morales',
    'Morales',
    'Morelia',
    'Morroa',
    'Mosquera',
    'Mosquera',
    'Motavita',
    'Murillo',
    'Murindó',
    'Mutatá',
    'Mutiscua',
    'Muzo',
    'Nariño',
    'Nariño',
    'Nariño',
    'Nátaga',
    'Natagaima',
    'Nechí',
    'Necoclí',
    'Neira',
    'Neiva',
    'Nemocón',
    'Nilo',
    'Nimaima',
    'Nobsa',
    'Nocaima',
    'Norcasia',
    'Norosí',
    'Nóvita',
    'Nueva Granada',
    'Nuevo Colón',
    'Nunchía',
    'Nuquí',
    'Obando',
    'Ocamonte',
    'Ocaña',
    'Oiba',
    'Oicatá',
    'Olaya',
    'Olaya Herrera',
    'Onzaga',
    'Oporapa',
    'Orito',
    'Orocué',
    'Ortega',
    'Ospina',
    'Otanche',
    'Ovejas',
    'Pachavita',
    'Pacho',
    'Pácora',
    'Padilla',
    'Páez',
    'Páez',
    'Paicol',
    'Pailitas',
    'Paime',
    'Paipa',
    'Pajarito',
    'Palermo',
    'Palestina',
    'Palestina',
    'Palmar de Varela',
    'Palmar',
    'Palmas del Socorro',
    'Palmira',
    'Palocabildo',
    'Pamplona',
    'Pamplonita',
    'Pandi',
    'Panqueba',
    'Páramo',
    'Paratebueno',
    'Pasca',
    'Pasto',
    'Patía',
    'Pauna',
    'Paya',
    'Paz de Ariporo',
    'Paz del Río',
    'Pedraza',
    'Pelaya',
    'Pensilvania',
    'Peque',
    'Pereira',
    'Pesca',
    'Piamonte',
    'Piedecuesta',
    'Piedras',
    'Piendamó',
    'Pijao',
    'Pijiño del Carmen',
    'Pinchote',
    'Pinillos',
    'Piojó',
    'Pisba',
    'Pitalito',
    'Pivijay',
    'Planadas',
    'Planeta Rica',
    'Plato',
    'Policarpa',
    'Polonuevo',
    'Ponedera',
    'Popayán',
    'Pore',
    'Potosí',
    'Pradera',
    'Prado',
    'Providencia',
    'Providencia y Santa Catalina Islas',
    'Pueblo Viejo',
    'Pueblo Bello',
    'Pueblo Nuevo',
    'Pueblo Rico',
    'Pueblorrico',
    'Puente Nacional',
    'Puerres',
    'Puerto Asís',
    'Puerto Berrío',
    'Puerto Boyacá',
    'Puerto Caicedo',
    'Puerto Carreño',
    'Puerto Colombia',
    'Puerto Concordia',
    'Puerto Escondido',
    'Puerto Gaitán',
    'Puerto Guzmán',
    'Puerto Leguízamo',
    'Puerto Libertador',
    'Puerto Lleras',
    'Puerto López',
    'Puerto Milán',
    'Puerto Nare',
    'Puerto Nariño',
    'Puerto Parra',
    'Puerto Rico',
    'Puerto Rico',
    'Puerto Rondón',
    'Puerto Salgar',
    'Puerto Santander',
    'Puerto Tejada',
    'Puerto Triunfo',
    'Puerto Wilches',
    'Pulí',
    'Pupiales',
    'Puracé',
    'Purificación',
    'Purísima',
    'Quebradanegra',
    'Quetame',
    'Quibdó',
    'Quimbaya',
    'Quinchía',
    'Quípama',
    'Quipile',
    'Ragonvalia',
    'Ramiriquí',
    'Ráquira',
    'Recetor',
    'Regidor',
    'Remedios',
    'Remolino',
    'Repelón',
    'Restrepo',
    'Restrepo',
    'Ricaurte',
    'Ricaurte',
    'Río de Oro',
    'Río Iró',
    'Río Quito',
    'Río Viejo',
    'Rioblanco',
    'Riofrío',
    'Riohacha',
    'Rionegro',
    'Rionegro',
    'Riosucio',
    'Riosucio',
    'Risaralda',
    'Rivera',
    'Roberto Payán',
    'Roldanillo',
    'Roncesvalles',
    'Rondón',
    'Rosas',
    'Rovira',
    'Sabana de Torres',
    'Sabanas de San Ángel',
    'Sabanagrande',
    'Sabanalarga',
    'Sabanalarga',
    'Sabanalarga',
    'Sabaneta',
    'Saboyá',
    'Sácama',
    'Sáchica',
    'Sahagún',
    'Saladoblanco',
    'Salamina',
    'Salamina',
    'Salazar de Las Palmas',
    'Saldaña',
    'Salento',
    'Salgar',
    'Samacá',
    'Samaná',
    'Samaniego',
    'Sampués',
    'San Agustín',
    'San Alberto',
    'San Andrés',
    'San Andrés',
    'San Andrés de Cuerquia',
    'San Andrés de Sotavento',
    'San Antero',
    'San Antonio',
    'San Antonio de Palmito',
    'San Antonio del Tequendama',
    'San Benito',
    'San Benito Abad',
    'San Bernardo',
    'San Bernardo',
    'San Bernardo del Viento',
    'San Calixto',
    'San Carlos',
    'San Carlos',
    'San Carlos de Guaroa',
    'San Cayetano',
    'San Cayetano',
    'San Cristóbal',
    'San Diego',
    'San Eduardo',
    'San Estanislao',
    'San Fernando',
    'San Francisco',
    'San Francisco',
    'San Francisco',
    'San Gil',
    'San Jacinto del Cauca',
    'San Jacinto',
    'San Jerónimo',
    'San Joaquín',
    'San José',
    'San José de Albán',
    'San José de Miranda',
    'San José de Pare',
    'San José de Uré',
    'San José de la Montaña',
    'San José del Fragua',
    'San José del Guaviare',
    'San José del Palmar',
    'San Juan de Arama',
    'San Juan de Betulia',
    'San Juan de Rioseco',
    'San Juan de Urabá',
    'San Juan del Cesar',
    'San Juan Nepomuceno',
    'San Juanito',
    'San Lorenzo',
    'San Luis',
    'San Luis',
    'San Luis de Gaceno',
    'San Luis de Palenque',
    'San Marcos',
    'San Martín',
    'San Martín',
    'San Martín de Loba',
    'San Mateo',
    'San Miguel',
    'San Miguel',
    'San Miguel de Sema',
    'San Onofre',
    'San Pablo',
    'San Pablo',
    'San Pablo de Borbur',
    'San Pedro',
    'San Pedro',
    'San Pedro de Cartago',
    'San Pedro de Urabá',
    'San Pedro de los Milagros',
    'San Pelayo',
    'San Rafael',
    'San Roque',
    'San Sebastián',
    'San Sebastián de Buenavista',
    'San Vicente',
    'San Vicente de Chucurí',
    'San Vicente del Caguán',
    'San Zenón',
    'Sandoná',
    'Santa Ana',
    'Santa Bárbara',
    'Santa Bárbara',
    'Santa Bárbara',
    'Santa Bárbara de Pinto',
    'Santa Catalina',
    'Santa Fe de Antioquia',
    'Santa Helena del Opón',
    'Santa Isabel',
    'Santa Lucía',
    'Santa María',
    'Santa María',
    'Santa Marta',
    'Santa Rosa',
    'Santa Rosa',
    'Santa Rosa de Cabal',
    'Santa Rosa de Osos',
    'Santa Rosa de Viterbo',
    'Santa Rosa del Sur',
    'Santa Rosalía',
    'Santa Sofía',
    'Santacruz',
    'Santana',
    'Santander de Quilichao',
    'Santiago',
    'Santiago',
    'Santo Domingo',
    'Santo Domingo de Silos',
    'Santo Tomás',
    'Santuario',
    'Sapuyes',
    'Saravena',
    'Sardinata',
    'Sasaima',
    'Sativanorte',
    'Sativasur',
    'Segovia',
    'Sesquilé',
    'Sevilla',
    'Siachoque',
    'Sibaté',
    'Sibundoy',
    'Silvania',
    'Silvia',
    'Simacota',
    'Simijaca',
    'Simití',
    'Sincé',
    'Sincelejo',
    'Sipí',
    'Sitionuevo',
    'Soacha',
    'Soatá',
    'Socha',
    'Socotá',
    'Sogamoso',
    'Solano',
    'Soledad',
    'Solita',
    'Somondoco',
    'Sonsón',
    'Sopetrán',
    'Soplaviento',
    'Sopó',
    'Sora',
    'Soracá',
    'Sotaquirá',
    'Sotará',
    'Suaita',
    'Suán',
    'Suárez',
    'Suárez',
    'Suaza',
    'Subachoque',
    'Sucre',
    'Sucre',
    'Sucre',
    'Suesca',
    'Supatá',
    'Supía',
    'Suratá',
    'Susa',
    'Susacón',
    'Sutamarchán',
    'Sutatausa',
    'Sutatenza',
    'Tabio',
    'Tadó',
    'Talaigua Nuevo',
    'Tamalameque',
    'Támara',
    'Tame',
    'Támesis',
    'Taminango',
    'Tangua',
    'Tarazá',
    'Tarquí',
    'Tarso',
    'Tasco',
    'Taraira',
    'Tauramena',
    'Tausa',
    'Tello',
    'Tena',
    'Tenerife',
    'Tenjo',
    'Tenza',
    'Teorama',
    'Teruel',
    'Tesalia',
    'Tibacuy',
    'Tibaná',
    'Tibasosa',
    'Tibirita',
    'Tibú',
    'Tierralta',
    'Timaná',
    'Timbío',
    'Timbiquí',
    'Tinjacá',
    'Tipacoque',
    'Tiquisio',
    'Titiribí',
    'Toca',
    'Tocaima',
    'Tocancipá',
    'Togüí',
    'Toledo',
    'Toledo',
    'Tolú',
    'Tolú Viejo',
    'Tona',
    'Tópaga',
    'Topaipí',
    'Toribío',
    'Toro',
    'Tota',
    'Totoró',
    'Trinidad',
    'Trujillo',
    'Tubará',
    'Tuchín',
    'Tuluá',
    'Tumaco',
    'Tunja',
    'Tununguá',
    'Túquerres',
    'Turbaco',
    'Turbaná',
    'Turbo',
    'Turmequé',
    'Tuta',
    'Tutazá',
    'Ubalá',
    'Ubaque',
    'Ubaté',
    'Ulloa',
    'Úmbita',
    'Une',
    'Unión Panamericana',
    'Unguía',
    'Uramita',
    'Uribia',
    'Urrao',
    'Urumita',
    'Usiacurí',
    'Útica',
    'Valdivia',
    'Valencia',
    'Valle de San José',
    'Valle de San Juan',
    'Valle del Guamuez',
    'Valledupar',
    'Valparaíso',
    'Valparaíso',
    'Vegachí',
    'Vélez',
    'Venadillo',
    'Venecia',
    'Venecia',
    'Ventaquemada',
    'Vergara',
    'Versalles',
    'Vetas',
    'Vianí',
    'Victoria',
    'Vigía del Fuerte',
    'Vijes',
    'Villa Caro',
    'Villa de Leyva',
    'Villa del Rosario',
    'Villa Rica',
    'Villagarzón',
    'Villagómez',
    'Villahermosa',
    'Villamaría',
    'Villanueva',
    'Villanueva',
    'Villanueva',
    'Villanueva',
    'Villapinzón',
    'Villarrica',
    'Villavicencio',
    'Villavieja',
    'Villeta',
    'Viotá',
    'Viracachá',
    'Vista Hermosa',
    'Viterbo',
    'Yacopí',
    'Yacuanquer',
    'Yaguará',
    'Yalí',
    'Yarumal',
    'Yolombó',
    'Yondó',
    'Yopal',
    'Yotoco',
    'Yumbo',
    'Zambrano',
    'Zapatoca',
    'Zapayán',
    'Zaragoza',
    'Zarzal',
    'Zetaquirá',
    'Zipacón',
    'Zipaquirá',
    'Zona Bananera',
    'Barranco Minas',
    'Cacahual',
    'El Encanto',
    'La Chorrera',
    'La Guadalupe',
    'La Pedrera',
    'La Victoria',
    'Mapiripana',
    'Mirití-Paraná',
    'Morichal Nuevo',
    'Pacoa',
    'Pana Pana',
    'Papunaua',
    'Puerto Alegría',
    'Puerto Arica',
    'Puerto Colombia',
    'Puerto Santander',
    'San Felipe',
    'Tarapacá',
    'Yavaraté'
  ];
}
