export class OptionsList {
  public static identificationTypes = [
    { name: 'Cédula de Ciudadanía', value: 'CC' },
    { name: 'Cédula de Extranjería', value: 'CE' },
    { name: 'Registro Civil', value: 'RC' },
    { name: 'Tarjeta de Identidad', value: 'TI' }
  ];

  public static addressUses = [
    { name: 'Casa', value: 'home' },
    { name: 'Oficina', value: 'work' },
    { name: 'Temporal', value: 'temp' },
    { name: 'Antiguo', value: 'old' },
    { name: 'Facturación', value: 'billing'}
  ];

  public static contactPointUses = [
    { name: 'Casa', value: 'home' },
    { name: 'Oficina', value: 'work' },
    { name: 'Temporal', value: 'temp' },
    { name: 'Anterior', value: 'old' },
    { name: 'Celular', value: 'mobile' }
  ];

  public static contactPointSystems = [
    { name: 'Teléfono', value: 'phone' },
    { name: 'Fax', value: 'fax' },
    { name: 'Email', value: 'email' },
    { name: 'SMS', value: 'sms' },
    { name: 'Otro', value: 'other' }
  ];

  public static clinicalStatus = [
    { name: 'Activo', value: 'active' },
    { name: 'Inactivo', value: 'inactive' },
    { name: 'Resuelto', value: 'resolved' }
  ];

  public static verificationStatus = [
    { name: 'No confirmado', value: 'unconfirmed' },
    { name: 'Confirmado', value: 'confirmed' },
    { name: 'Refutado', value: 'refuted' },
    { name: 'Ingresado por error', value: 'entered-in-error' }
  ];

  public static AllergyIntoleranceType = [
    { name: 'Alergia', value: 'allergy' },
    { name: 'Intolerancia', value: 'intolerance' }
  ];

  public static AllergyIntoleranceCategory = [
    { name: 'Comida', value: 'food' },
    { name: 'Medicación', value: 'medication' },
    { name: 'Ambiente', value: 'environment' },
    { name: 'Biologico', value: 'biologic' }
  ];

  public static AllergyIntoleranceCriticality = [
    { name: 'Bajo riesgo', value: 'low' },
    { name: 'Alto riesgo', value: 'high' },
    { name: 'No se puede evaluar', value: 'unable-to-assess' }
  ];

  public static AllergyIntoleranceCode = [
    { name: 'Hemoglobina okaloosa', value: '102002 ' },
    { name: 'Carrera de ornitina', value: '120006 ' },
    { name: 'Sulfato ferroso Fe ^ 59 ^', value: '125001 ' },
    { name: 'Galactosil-N-acetilglucosaminilgalactosilglucosilceramida alfa-galactosiltransferasa', value: '126000 ' },
    { name: 'Hemoglobina Hopkins-II', value: '130002 ' },
    { name: 'Manosiltransferasa de dolilfosfato', value: '131003 ' },
    { name: 'Sal de ferrocianuro', value: '159002 ' },
    { name: 'Fosfoenolpiruvato-proteína fosfotransferasa', value: '164003 ' },
    { name: 'Uridil difosfato galactosa', value: '178002 ' },
    { name: 'Antígeno HLA-Cw9', value: '186002 ' }
  ];

  public static AllergyIntoleranceSeverity = [
    { name: 'Leve', value: 'mild' },
    { name: 'Moderada', value: 'moderate' },
    { name: 'Grave', value: 'severe' },
  ];

  public static ExposureRouteCodes = [
    { name: 'Topical route', value: '6064005 ' },
    { name: 'Auricular use', value: '10547007 ' },
    { name: 'Intra-articular route', value: '12130007 ' },
    { name: 'Oral use', value: '26643006 ' },
    { name: 'SC use', value: '34206005 ' },
    { name: 'Rectal use', value: '37161004 ' },
    { name: 'Intraluminal use', value: '37737002 ' },
    { name: 'Sublingual use', value: '37839007 ' },
    { name: 'Intraperitoneal use', value: '38239002 ' },
    { name: 'Transdermal use', value: '45890007 ' }
  ];

  public static cities: string[] = [
    'Abejorral',
    'Ábrego',
    'Abriaquí',
    'Acacías',
    'Acandí',
    'Acevedo',
    'Achí',
    'Agrado',
    'Agua de Dios',
    'Aguachica',
    'Aguada',
    'Aguadas',
    'Aguazul',
    'Agustín Codazzi',
    'Aipe',
    'Albán',
    'Albania',
    'Albania',
    'Albania',
    'Alcalá',
    'Aldana',
    'Alejandría',
    'Algarrobo',
    'Algeciras',
    'Almaguer',
    'Almeida',
    'Alpujarra',
    'Altamira',
    'Alto Baudó',
    'Altos del Rosario',
    'Alvarado',
    'Amagá',
    'Amalfi',
    'Ambalema',
    'Anapoima',
    'Ancuya',
    'Andalucía',
    'Andes',
    'Angelópolis',
    'Angostura',
    'Anolaima',
    'Anorí',
    'Anserma',
    'Ansermanuevo',
    'Anzá',
    'Anzoátegui',
    'Apartadó',
    'Apía',
    'Apulo',
    'Aquitania',
    'Aracataca',
    'Aranzazu',
    'Aratoca',
    'Arauca',
    'Arauquita',
    'Arbeláez',
    'Arboleda',
    'Arboledas',
    'Arboletes',
    'Arcabuco',
    'Arenal',
    'Argelia',
    'Argelia',
    'Argelia',
    'Ariguaní',
    'Arjona',
    'Armenia',
    'Armenia',
    'Armero',
    'Arroyohondo',
    'Astrea',
    'Ataco',
    'Ayapel',
    'Bagadó',
    'Bahía Solano',
    'Bajo Baudó',
    'Balboa',
    'Balboa',
    'Baranoa',
    'Baraya',
    'Barbacoas',
    'Barbosa',
    'Barbosa',
    'Barichara',
    'Barranca de Upía',
    'Barrancabermeja',
    'Barrancas',
    'Barranco de Loba',
    'Barranquilla',
    'Becerril',
    'Belalcázar',
    'Belén',
    'Belén',
    'Belén de los Andaquíes',
    'Belén de Umbría',
    'Bello',
    'Belmira',
    'Beltrán',
    'Berbeo',
    'Betania',
    'Betéitiva',
    'Betulia',
    'Betulia',
    'Bituima',
    'Boavita',
    'Bochalema',
    'Bogotá',
    'Bojacá',
    'Bojayá',
    'Bolívar',
    'Bolívar',
    'Bolívar',
    'Bolívar',
    'Bosconia',
    'Boyacá',
    'Brazuelo de Papayal',
    'Briceño',
    'Briceño',
    'Bucaramanga',
    'Bucarasica',
    'Buenaventura',
    'Buenavista',
    'Buenavista',
    'Buenavista',
    'Buenavista',
    'Buenos Aires',
    'Buesaco',
    'Buga',
    'Bugalagrande',
    'Buriticá',
    'Busbanzá',
    'Cabrera',
    'Cabrera',
    'Cabuyaro',
    'Cáceres',
    'Cachipay',
    'Cáchira',
    'Cácota',
    'Caicedo',
    'Caicedonia',
    'Caimito',
    'Cajamarca',
    'Cajibío',
    'Cajicá',
    'Calamar',
    'Calamar',
    'Calarcá',
    'Caldas',
    'Caldas',
    'Caldono',
    'Cali',
    'California',
    'Calima',
    'Caloto',
    'Campamento',
    'Campo de la Cruz',
    'Campoalegre',
    'Campohermoso',
    'Canalete',
    'Candelaria',
    'Candelaria',
    'Cantagallo',
    'Cantón de San Pablo',
    'Cañasgordas',
    'Caparrapí',
    'Capitanejo',
    'Cáqueza',
    'Caracolí',
    'Caramanta',
    'Carcasí',
    'Carepa',
    'Carmen de Apicalá',
    'Carmen de Carupa',
    'Carolina del Príncipe',
    'Cartagena de Indias',
    'Cartagena del Chairá',
    'Cartago',
    'Carurú',
    'Casabianca',
    'Castilla la Nueva',
    'Caucasia',
    'Cepitá',
    'Cereté',
    'Cerinza',
    'Cerrito',
    'Cerro de San Antonio',
    'Cértegui',
    'Chachagüí',
    'Chaguaní',
    'Chalán',
    'Chámeza',
    'Chaparral',
    'Charalá',
    'Charta',
    'Chía',
    'Chibolo',
    'Chigorodó',
    'Chima',
    'Chimá',
    'Chimichagua',
    'Chinácota',
    'Chinavita',
    'Chinchiná',
    'Chinú',
    'Chipaque',
    'Chipatá',
    'Chiquinquirá',
    'Chíquiza',
    'Chiriguaná',
    'Chiscas',
    'Chita',
    'Chitagá',
    'Chitaraque',
    'Chivatá',
    'Chivolo',
    'Chivor',
    'Choachí',
    'Chocontá',
    'Cicuco',
    'Ciénaga',
    'Ciénaga de Oro',
    'Ciénega',
    'Cimitarra',
    'Circasia',
    'Cisneros',
    'Clemencia',
    'Cocorná',
    'Coello',
    'Cogua',
    'Colombia',
    'Colón',
    'Colón',
    'Colosó',
    'Cómbita',
    'Concepción',
    'Concepción',
    'Concordia',
    'Concordia',
    'Condoto',
    'Confines',
    'Consacá',
    'Contadero',
    'Contratación',
    'Convención',
    'Copacabana',
    'Coper',
    'Córdoba',
    'Córdoba',
    'Córdoba',
    'Corinto',
    'Coromoro',
    'Corozal',
    'Corrales',
    'Cota',
    'Cotorra',
    'Covarachía',
    'Coveñas',
    'Coyaima',
    'Cravo Norte',
    'Cuaspud',
    'Cubará',
    'Cubarral',
    'Cucaita',
    'Cucunubá',
    'Cúcuta',
    'Cucutilla',
    'Cuítiva',
    'Cumaral',
    'Cumaribo',
    'Cumbal',
    'Cumbitara',
    'Cunday',
    'Curillo',
    'Curití',
    'Curumaní',
    'Dabeiba',
    'Dagua',
    'Dibulla',
    'Distracción',
    'Dolores',
    'Donmatías',
    'Dosquebradas',
    'Duitama',
    'Duranía',
    'Ebéjico',
    'El Águila',
    'El Atrato',
    'El Bagre',
    'El Banco',
    'El Cairo',
    'El Calvario',
    'El Carmen',
    'El Carmen de Atrato',
    'El Carmen de Bolívar',
    'El Carmen de Chucurí',
    'El Carmen de Viboral',
    'El Carmen del Darién',
    'El Castillo',
    'El Cerrito',
    'El Charco',
    'El Cocuy',
    'El Colegio',
    'El Copey',
    'El Doncello',
    'El Dorado',
    'El Dovio',
    'El Espinal',
    'El Espino',
    'El Guacamayo',
    'El Guamo',
    'El Molino',
    'El Paso',
    'El Paujil',
    'El Peñol',
    'El Peñol',
    'El Peñón',
    'El Peñón',
    'El Peñón',
    'El Piñón',
    'El Pital',
    'El Playón',
    'El Retén',
    'El Retiro',
    'El Retorno',
    'El Roble',
    'El Rosal',
    'El Rosario',
    'El Santuario',
    'El Socorro',
    'El Tablón',
    'El Tambo',
    'El Tambo',
    'El Tarra',
    'El Zulia',
    'Elías',
    'Encino',
    'Entrerríos',
    'Envigado',
    'Facatativá',
    'Falán',
    'Filadelfia',
    'Filandia',
    'Firavitoba',
    'Flandes',
    'Florencia',
    'Florencia',
    'Floresta',
    'Florián',
    'Florida',
    'Floridablanca',
    'Fómeque',
    'Fonseca',
    'Fortul',
    'Fosca',
    'Francisco Pizarro',
    'Fredonia',
    'Fresno',
    'Frontino',
    'Fuente de Oro',
    'Fundación',
    'Funes',
    'Funza',
    'Fúquene',
    'Fusagasugá',
    'Gachalá',
    'Gachancipá',
    'Gachantivá',
    'Gachetá',
    'Galán',
    'Galapa',
    'Galeras',
    'Gama',
    'Gamarra',
    'Gámbita',
    'Gámeza',
    'Garagoa',
    'Garzón',
    'Génova',
    'Gigante',
    'Ginebra',
    'Giraldo',
    'Girardot',
    'Girardota',
    'Girón',
    'Gómez Plata',
    'González',
    'Gramalote',
    'Granada',
    'Granada',
    'Granada',
    'Guaca',
    'Guacamayas',
    'Guacarí',
    'Guachené',
    'Guachetá',
    'Guachucal',
    'Guadalupe',
    'Guadalupe',
    'Guadalupe',
    'Guaduas',
    'Guaitarilla',
    'Gualmatán',
    'Guamal',
    'Guamal',
    'Guamo',
    'Guapí',
    'Guapotá',
    'Guaranda',
    'Guarne',
    'Guasca',
    'Guatapé',
    'Guataquí',
    'Guatavita',
    'Guateque',
    'Guática',
    'Guavatá',
    'Guayabal de Síquima',
    'Guayabetal',
    'Guayatá',
    'Güepsa',
    'Güicán',
    'Gutiérrez',
    'Hacarí',
    'Hatillo de Loba',
    'Hato Corozal',
    'Hato',
    'Hatonuevo',
    'Heliconia',
    'Herrán',
    'Herveo',
    'Hispania',
    'Hobo',
    'Honda',
    'Ibagué',
    'Icononzo',
    'Iles',
    'Imués',
    'Inírida',
    'Inzá',
    'Ipiales',
    'Íquira',
    'Isnos',
    'Itagüí',
    'Istmina',
    'Ituango',
    'Iza',
    'Jambaló',
    'Jamundí',
    'Jardín',
    'Jenesano',
    'Jericó',
    'Jericó',
    'Jerusalén',
    'Jesús María',
    'Jordán',
    'Juan de Acosta',
    'Junín',
    'Juradó',
    'La Apartada',
    'La Argentina',
    'La Belleza',
    'La Calera',
    'La Capilla',
    'La Ceja',
    'La Celia',
    'La Cruz',
    'La Cumbre',
    'La Dorada',
    'La Esperanza',
    'La Estrella',
    'La Florida',
    'La Gloria (Cesar)',
    'La Jagua de Ibirico',
    'La Jagua del Pilar',
    'La Llanada',
    'La Macarena',
    'La Merced',
    'La Mesa',
    'La Montañita',
    'La Palma',
    'La Paz',
    'La Paz',
    'La Peña',
    'La Pintada',
    'La Plata',
    'La Playa de Belén',
    'La Primavera',
    'La Salina',
    'La Sierra',
    'La Tebaida',
    'La Tola',
    'La Uvita',
    'La Unión',
    'La Unión',
    'La Unión',
    'La Unión',
    'La Uribe',
    'La Vega',
    'La Vega',
    'La Victoria',
    'La Victoria',
    'La Virginia',
    'Labateca',
    'Labranzagrande',
    'Landázuri',
    'Lebrija',
    'Leiva',
    'Lejanías',
    'Lenguazaque',
    'Lérida',
    'Leticia',
    'Líbano',
    'Liborina',
    'Linares',
    'Litoral de San Juan',
    'Lloró',
    'López de Micay',
    'Lorica',
    'Los Andes',
    'Los Córdobas',
    'Los Palmitos',
    'Los Patios',
    'Los Santos',
    'Lourdes',
    'Luruaco',
    'Macanal',
    'Macaravita',
    'Maceo',
    'Machetá',
    'Madrid',
    'Magangué',
    'Magüí Payán',
    'Mahates',
    'Maicao',
    'Majagual',
    'Málaga',
    'Malambo',
    'Mallama',
    'Manatí',
    'Manaure Balcón del Cesar',
    'Manaure',
    'Maní',
    'Manizales',
    'Manta',
    'Manzanares',
    'Mapiripán',
    'Margarita',
    'María la Baja',
    'Marinilla',
    'Maripí',
    'Mariquita',
    'Marmato',
    'Marquetalia',
    'Marsella',
    'Marulanda',
    'Matanza',
    'Medellín',
    'Medio Atrato',
    'Medio Baudó',
    'Medio San Juan',
    'Medina',
    'Melgar',
    'Mercaderes',
    'Mesetas',
    'Miraflores',
    'Miraflores',
    'Miranda',
    'Mistrató',
    'Mitú',
    'Mocoa',
    'Mogotes',
    'Molagavita',
    'Momil',
    'Mompós',
    'Mongua',
    'Monguí',
    'Moniquirá',
    'Montebello',
    'Montecristo',
    'Montelíbano',
    'Montenegro',
    'Montería',
    'Monterrey',
    'Moñitos',
    'Morales',
    'Morales',
    'Morelia',
    'Morroa',
    'Mosquera',
    'Mosquera',
    'Motavita',
    'Murillo',
    'Murindó',
    'Mutatá',
    'Mutiscua',
    'Muzo',
    'Nariño',
    'Nariño',
    'Nariño',
    'Nátaga',
    'Natagaima',
    'Nechí',
    'Necoclí',
    'Neira',
    'Neiva',
    'Nemocón',
    'Nilo',
    'Nimaima',
    'Nobsa',
    'Nocaima',
    'Norcasia',
    'Norosí',
    'Nóvita',
    'Nueva Granada',
    'Nuevo Colón',
    'Nunchía',
    'Nuquí',
    'Obando',
    'Ocamonte',
    'Ocaña',
    'Oiba',
    'Oicatá',
    'Olaya',
    'Olaya Herrera',
    'Onzaga',
    'Oporapa',
    'Orito',
    'Orocué',
    'Ortega',
    'Ospina',
    'Otanche',
    'Ovejas',
    'Pachavita',
    'Pacho',
    'Pácora',
    'Padilla',
    'Páez',
    'Páez',
    'Paicol',
    'Pailitas',
    'Paime',
    'Paipa',
    'Pajarito',
    'Palermo',
    'Palestina',
    'Palestina',
    'Palmar de Varela',
    'Palmar',
    'Palmas del Socorro',
    'Palmira',
    'Palocabildo',
    'Pamplona',
    'Pamplonita',
    'Pandi',
    'Panqueba',
    'Páramo',
    'Paratebueno',
    'Pasca',
    'Pasto',
    'Patía',
    'Pauna',
    'Paya',
    'Paz de Ariporo',
    'Paz del Río',
    'Pedraza',
    'Pelaya',
    'Pensilvania',
    'Peque',
    'Pereira',
    'Pesca',
    'Piamonte',
    'Piedecuesta',
    'Piedras',
    'Piendamó',
    'Pijao',
    'Pijiño del Carmen',
    'Pinchote',
    'Pinillos',
    'Piojó',
    'Pisba',
    'Pitalito',
    'Pivijay',
    'Planadas',
    'Planeta Rica',
    'Plato',
    'Policarpa',
    'Polonuevo',
    'Ponedera',
    'Popayán',
    'Pore',
    'Potosí',
    'Pradera',
    'Prado',
    'Providencia',
    'Providencia y Santa Catalina Islas',
    'Pueblo Viejo',
    'Pueblo Bello',
    'Pueblo Nuevo',
    'Pueblo Rico',
    'Pueblorrico',
    'Puente Nacional',
    'Puerres',
    'Puerto Asís',
    'Puerto Berrío',
    'Puerto Boyacá',
    'Puerto Caicedo',
    'Puerto Carreño',
    'Puerto Colombia',
    'Puerto Concordia',
    'Puerto Escondido',
    'Puerto Gaitán',
    'Puerto Guzmán',
    'Puerto Leguízamo',
    'Puerto Libertador',
    'Puerto Lleras',
    'Puerto López',
    'Puerto Milán',
    'Puerto Nare',
    'Puerto Nariño',
    'Puerto Parra',
    'Puerto Rico',
    'Puerto Rico',
    'Puerto Rondón',
    'Puerto Salgar',
    'Puerto Santander',
    'Puerto Tejada',
    'Puerto Triunfo',
    'Puerto Wilches',
    'Pulí',
    'Pupiales',
    'Puracé',
    'Purificación',
    'Purísima',
    'Quebradanegra',
    'Quetame',
    'Quibdó',
    'Quimbaya',
    'Quinchía',
    'Quípama',
    'Quipile',
    'Ragonvalia',
    'Ramiriquí',
    'Ráquira',
    'Recetor',
    'Regidor',
    'Remedios',
    'Remolino',
    'Repelón',
    'Restrepo',
    'Restrepo',
    'Ricaurte',
    'Ricaurte',
    'Río de Oro',
    'Río Iró',
    'Río Quito',
    'Río Viejo',
    'Rioblanco',
    'Riofrío',
    'Riohacha',
    'Rionegro',
    'Rionegro',
    'Riosucio',
    'Riosucio',
    'Risaralda',
    'Rivera',
    'Roberto Payán',
    'Roldanillo',
    'Roncesvalles',
    'Rondón',
    'Rosas',
    'Rovira',
    'Sabana de Torres',
    'Sabanas de San Ángel',
    'Sabanagrande',
    'Sabanalarga',
    'Sabanalarga',
    'Sabanalarga',
    'Sabaneta',
    'Saboyá',
    'Sácama',
    'Sáchica',
    'Sahagún',
    'Saladoblanco',
    'Salamina',
    'Salamina',
    'Salazar de Las Palmas',
    'Saldaña',
    'Salento',
    'Salgar',
    'Samacá',
    'Samaná',
    'Samaniego',
    'Sampués',
    'San Agustín',
    'San Alberto',
    'San Andrés',
    'San Andrés',
    'San Andrés de Cuerquia',
    'San Andrés de Sotavento',
    'San Antero',
    'San Antonio',
    'San Antonio de Palmito',
    'San Antonio del Tequendama',
    'San Benito',
    'San Benito Abad',
    'San Bernardo',
    'San Bernardo',
    'San Bernardo del Viento',
    'San Calixto',
    'San Carlos',
    'San Carlos',
    'San Carlos de Guaroa',
    'San Cayetano',
    'San Cayetano',
    'San Cristóbal',
    'San Diego',
    'San Eduardo',
    'San Estanislao',
    'San Fernando',
    'San Francisco',
    'San Francisco',
    'San Francisco',
    'San Gil',
    'San Jacinto del Cauca',
    'San Jacinto',
    'San Jerónimo',
    'San Joaquín',
    'San José',
    'San José de Albán',
    'San José de Miranda',
    'San José de Pare',
    'San José de Uré',
    'San José de la Montaña',
    'San José del Fragua',
    'San José del Guaviare',
    'San José del Palmar',
    'San Juan de Arama',
    'San Juan de Betulia',
    'San Juan de Rioseco',
    'San Juan de Urabá',
    'San Juan del Cesar',
    'San Juan Nepomuceno',
    'San Juanito',
    'San Lorenzo',
    'San Luis',
    'San Luis',
    'San Luis de Gaceno',
    'San Luis de Palenque',
    'San Marcos',
    'San Martín',
    'San Martín',
    'San Martín de Loba',
    'San Mateo',
    'San Miguel',
    'San Miguel',
    'San Miguel de Sema',
    'San Onofre',
    'San Pablo',
    'San Pablo',
    'San Pablo de Borbur',
    'San Pedro',
    'San Pedro',
    'San Pedro de Cartago',
    'San Pedro de Urabá',
    'San Pedro de los Milagros',
    'San Pelayo',
    'San Rafael',
    'San Roque',
    'San Sebastián',
    'San Sebastián de Buenavista',
    'San Vicente',
    'San Vicente de Chucurí',
    'San Vicente del Caguán',
    'San Zenón',
    'Sandoná',
    'Santa Ana',
    'Santa Bárbara',
    'Santa Bárbara',
    'Santa Bárbara',
    'Santa Bárbara de Pinto',
    'Santa Catalina',
    'Santa Fe de Antioquia',
    'Santa Helena del Opón',
    'Santa Isabel',
    'Santa Lucía',
    'Santa María',
    'Santa María',
    'Santa Marta',
    'Santa Rosa',
    'Santa Rosa',
    'Santa Rosa de Cabal',
    'Santa Rosa de Osos',
    'Santa Rosa de Viterbo',
    'Santa Rosa del Sur',
    'Santa Rosalía',
    'Santa Sofía',
    'Santacruz',
    'Santana',
    'Santander de Quilichao',
    'Santiago',
    'Santiago',
    'Santo Domingo',
    'Santo Domingo de Silos',
    'Santo Tomás',
    'Santuario',
    'Sapuyes',
    'Saravena',
    'Sardinata',
    'Sasaima',
    'Sativanorte',
    'Sativasur',
    'Segovia',
    'Sesquilé',
    'Sevilla',
    'Siachoque',
    'Sibaté',
    'Sibundoy',
    'Silvania',
    'Silvia',
    'Simacota',
    'Simijaca',
    'Simití',
    'Sincé',
    'Sincelejo',
    'Sipí',
    'Sitionuevo',
    'Soacha',
    'Soatá',
    'Socha',
    'Socotá',
    'Sogamoso',
    'Solano',
    'Soledad',
    'Solita',
    'Somondoco',
    'Sonsón',
    'Sopetrán',
    'Soplaviento',
    'Sopó',
    'Sora',
    'Soracá',
    'Sotaquirá',
    'Sotará',
    'Suaita',
    'Suán',
    'Suárez',
    'Suárez',
    'Suaza',
    'Subachoque',
    'Sucre',
    'Sucre',
    'Sucre',
    'Suesca',
    'Supatá',
    'Supía',
    'Suratá',
    'Susa',
    'Susacón',
    'Sutamarchán',
    'Sutatausa',
    'Sutatenza',
    'Tabio',
    'Tadó',
    'Talaigua Nuevo',
    'Tamalameque',
    'Támara',
    'Tame',
    'Támesis',
    'Taminango',
    'Tangua',
    'Tarazá',
    'Tarquí',
    'Tarso',
    'Tasco',
    'Taraira',
    'Tauramena',
    'Tausa',
    'Tello',
    'Tena',
    'Tenerife',
    'Tenjo',
    'Tenza',
    'Teorama',
    'Teruel',
    'Tesalia',
    'Tibacuy',
    'Tibaná',
    'Tibasosa',
    'Tibirita',
    'Tibú',
    'Tierralta',
    'Timaná',
    'Timbío',
    'Timbiquí',
    'Tinjacá',
    'Tipacoque',
    'Tiquisio',
    'Titiribí',
    'Toca',
    'Tocaima',
    'Tocancipá',
    'Togüí',
    'Toledo',
    'Toledo',
    'Tolú',
    'Tolú Viejo',
    'Tona',
    'Tópaga',
    'Topaipí',
    'Toribío',
    'Toro',
    'Tota',
    'Totoró',
    'Trinidad',
    'Trujillo',
    'Tubará',
    'Tuchín',
    'Tuluá',
    'Tumaco',
    'Tunja',
    'Tununguá',
    'Túquerres',
    'Turbaco',
    'Turbaná',
    'Turbo',
    'Turmequé',
    'Tuta',
    'Tutazá',
    'Ubalá',
    'Ubaque',
    'Ubaté',
    'Ulloa',
    'Úmbita',
    'Une',
    'Unión Panamericana',
    'Unguía',
    'Uramita',
    'Uribia',
    'Urrao',
    'Urumita',
    'Usiacurí',
    'Útica',
    'Valdivia',
    'Valencia',
    'Valle de San José',
    'Valle de San Juan',
    'Valle del Guamuez',
    'Valledupar',
    'Valparaíso',
    'Valparaíso',
    'Vegachí',
    'Vélez',
    'Venadillo',
    'Venecia',
    'Venecia',
    'Ventaquemada',
    'Vergara',
    'Versalles',
    'Vetas',
    'Vianí',
    'Victoria',
    'Vigía del Fuerte',
    'Vijes',
    'Villa Caro',
    'Villa de Leyva',
    'Villa del Rosario',
    'Villa Rica',
    'Villagarzón',
    'Villagómez',
    'Villahermosa',
    'Villamaría',
    'Villanueva',
    'Villanueva',
    'Villanueva',
    'Villanueva',
    'Villapinzón',
    'Villarrica',
    'Villavicencio',
    'Villavieja',
    'Villeta',
    'Viotá',
    'Viracachá',
    'Vista Hermosa',
    'Viterbo',
    'Yacopí',
    'Yacuanquer',
    'Yaguará',
    'Yalí',
    'Yarumal',
    'Yolombó',
    'Yondó',
    'Yopal',
    'Yotoco',
    'Yumbo',
    'Zambrano',
    'Zapatoca',
    'Zapayán',
    'Zaragoza',
    'Zarzal',
    'Zetaquirá',
    'Zipacón',
    'Zipaquirá',
    'Zona Bananera',
    'Barranco Minas',
    'Cacahual',
    'El Encanto',
    'La Chorrera',
    'La Guadalupe',
    'La Pedrera',
    'La Victoria',
    'Mapiripana',
    'Mirití-Paraná',
    'Morichal Nuevo',
    'Pacoa',
    'Pana Pana',
    'Papunaua',
    'Puerto Alegría',
    'Puerto Arica',
    'Puerto Colombia',
    'Puerto Santander',
    'San Felipe',
    'Tarapacá',
    'Yavaraté'
  ];
}
