export enum RoleEnum {
    DOCTOR = 'ROLE_DOCTOR',
	NURSE = 'ROLE_NURSE',
	ADMINISTRATIVE_ASSISTANT = 'ROLE_ADMINISTRATIVE_ASSISTANT',
	ADMINISTRATOR = 'ROLE_ADMINISTRATOR',
    PATIENT = 'ROLE_PATIENT'
}